function [controlPort, dataPort, configFileName, liveDemoFlag, fileLoop] = configDialog      
comPortChoice = {'COM1',  'COM2',  'COM3',  'COM4',  'COM5',  'COM6',  'COM7',  'COM8',  'COM9', 'COM10',...
                 'COM11', 'COM12', 'COM13', 'COM14', 'COM15', 'COM16', 'COM17', 'COM18', 'COM19','COM20',...
                 'COM21', 'COM22', 'COM23', 'COM24', 'COM25', 'COM26', 'COM27', 'COM28', 'COM29','COM30',...
                 'COM31', 'COM32', 'COM33', 'COM34', 'COM35', 'COM36', 'COM37', 'COM38', 'COM39','COM40',...
                 'COM41', 'COM42', 'COM43', 'COM44', 'COM45', 'COM46', 'COM47', 'COM48', 'COM49','COM50',...
                 'COM51', 'COM52', 'COM53', 'COM54', 'COM55', 'COM56', 'COM57', 'COM58', 'COM59','COM60',...
                 'COM61', 'COM62', 'COM63', 'COM64', 'COM65', 'COM66', 'COM67', 'COM68', 'COM69','COM70',...
                 'COM71', 'COM72', 'COM73', 'COM74', 'COM75', 'COM76', 'COM77', 'COM78', 'COM79','COM80',...
                 'COM81', 'COM82', 'COM83', 'COM84', 'COM85', 'COM86', 'COM87', 'COM88', 'COM89','COM90',...
                 'COM91', 'COM92', 'COM93', 'COM94', 'COM95', 'COM96', 'COM97', 'COM98', 'COM99','COM100',...
                 };
configPathName = pwd;
configFileName = '.\config_file\major_motion_in_cabin_intruder.cfg';

hDialog = dialog('Position',[300 300 350 200],'Name','Configuration');
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 150 100 40],...
    'HorizontalAlignment','left',...
    'String','Select config & Data port');

uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 135 100 40],...
    'HorizontalAlignment','left',...
    'String','BaudRate = 115200');

popup1 = uicontrol('Parent',hDialog,...
    'Style','popup',...
    'Position',[20 130 100 25],...
    'String',comPortChoice,...
    'Value', 17);
% KNS - removed the second COM port 
% uicontrol('Parent',hDialog,...
%     'Style','text',...
%     'Position',[200 150 100 40],...
%     'HorizontalAlignment','left',...
%     'String','Select data port');

% uicontrol('Parent',hDialog,...
%     'Style','text',...
%     'Position',[200 135 100 40],...
%     'HorizontalAlignment','left',...
%     'String','BaudRate = 921600');

% popup2 = uicontrol('Parent',hDialog,...
%     'Style','popup',...
%     'Position',[200 130 100 25],...
%     'String', comPortChoice,...
%     'Value', 5);

uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 80 200 40],...
    'HorizontalAlignment','left',...
    'String','Select chirp configuration file');

hFileName = uicontrol('Parent', hDialog,...
    'Style','text',...
    'Position',[20 60 260 40],...
    'HorizontalAlignment','left',...
    'String', configFileName);

hFileSelect = uicontrol('Parent',hDialog,...
    'Style', 'pushbutton',...
    'Position',[300 80 40 20],...
    'String','...',...
    'Callback',@configFileSelect_callback);

setappdata(hFileSelect,'configFileName', [configPathName,'\', configFileName]);

modeChoice = {'Real Demo', 'Playback'};         
uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[20 40 100 20],...
    'HorizontalAlignment','left',...
    'String','Mode Selection');

modePopup = uicontrol('Parent',hDialog,...
    'Style','popup',...
    'Position',[20 20 100 20],...
    'String',modeChoice,...
    'Value', 1);
              
recordingFileChoice = {'1',  '2',  '3',  '4',  '5',  '6',  '7',  '8',  '9', '10',...
                 '11', '12', '13', '14', '15', '16', '17', '18', '19','20',...
                 };

uicontrol('Parent',hDialog,...
    'Style','text',...
    'Position',[150 40 150 20],...
    'HorizontalAlignment','left',...
    'String','Index for recording file');

popup3 = uicontrol('Parent',hDialog,...
    'Style','popup',...
    'Position',[150 20 50 20],...
    'String',recordingFileChoice,...
    'Value', 1);

uicontrol('Parent',hDialog,...
    'Position',[300 20 40 25],...
    'String','Go!',...
    'Callback',@go_callback);

% Wait for d to close before running to completion
uiwait(hDialog);

    function [pathname, filename] = configFileSelect_callback (source, ~)
        [filename, pathname] = uigetfile({'*.cfg'},...
            'Select Chirp configuration File', ...
            getappdata(source, 'configFileName'));
        hFileName.String = filename;
        setappdata(source, 'configFileName', [pathname, filename]);
    end
    function go_callback (~, ~)
        controlPort = popup1.Value;
        % KNS - uses the same COM port for both data and CLI commands 
		%dataPort = popup2.Value;
        dataPort = popup1.Value;
        
        modeSelect = modePopup.Value;
        configFileName = getappdata(hFileSelect, 'configFileName');
        fileLoop = popup3.Value;
        if (modeSelect == 1)
            liveDemoFlag = 1;
        else
            liveDemoFlag = 0;
        end
        delete(gcf);
    end
end
