function sendconfiguration(controlSerialPort, cliCfg, chirpConfigurationFileName)
    mmwDemoCliPrompt = char('vodDemo:/>');
    unsupported_commands = {'dynamicRACfarCfg' ...
                            'staticRACfarCfg' ...
                            'dynamicRangeAngleCfg' ...
                            'dynamic2DAngleCfg' ...
                            'staticRangeAngleCfg' ...
                            'antGeometry0' ...
                            'antGeometry1' ...
                            'antPhaseRot' ...
                            'fovCfg' ...
                            'numZones' ...
                            'totNumRows' ...
                            'sensorPosition' ...
                            'occStateMach' ...
                            'interiorBounds' ...
                            'cuboidDef' ...
                            'zoneNeighDef' ...
                            '%'};
    
    %Send Configuration Parameters to AWR68xx
    hControlSerialPort = configureControlPort(controlSerialPort);
    hDataSerialPort = hControlSerialPort;
    timeOut = get(hControlSerialPort,'Timeout');
    set(hControlSerialPort,'Timeout',1);
    %Send CLI configuration to AWR68xx
    fprintf('Sending configuration from %s file to AWRL6432 ...\n', chirpConfigurationFileName);
    for k=1:length(cliCfg)
        if (length(cliCfg{k}) > 1)

           % check if this commad is in the unsupported list of commands 
           C = strsplit(cliCfg{k});
           if (find(strcmp(unsupported_commands,C{1})))
            % string present in unsupported list. do not send to receiver 
                continue; 
           end
           fprintf(hControlSerialPort, cliCfg{k});
           fprintf('%s\n', cliCfg{k});
           echo = fgetl(hControlSerialPort); % Get an echo of a command
           done = fgetl(hControlSerialPort); % Get "Done"
           prompt = fread(hControlSerialPort, size(mmwDemoCliPrompt,2)); % Get the prompt back
        end
    end
    % KNS - Close the serial port after the configuration is sent to receiver. 
    fclose(hControlSerialPort);
    delete(hControlSerialPort);
end
